#pragma once

// Anti-aliased proportional fonts (DejaVu Sans) covering ASCII, Latin-1,
// Latin Extended-A, Romanian and Cyrillic, looked up by Unicode codepoint.
// No ESP-IDF dependencies, so it also compiles on the PC for the unit tests
// in test/. The glyph tables (font_data.c) are generated by
// tools/gen_font.py.

#include <stdint.h>

#define FONT_MISSING 0xFFFD // drawn for anything the font doesn't have

typedef struct {
    uint16_t cp;
    uint8_t w, h;    // bitmap size in px (0 for a space)
    int8_t x, y;     // bitmap top-left, from the pen position / the line top
    uint8_t advance; // pen movement to the next glyph
    uint32_t offset; // into font_t.bitmap
} font_glyph_t;

typedef struct {
    const font_glyph_t *glyphs; // sorted by cp
    int count;
    // 4 bits of coverage per px (0 = none, 15 = full), high nibble first,
    // each row starting on a fresh byte.
    const uint8_t *bitmap;
    uint8_t line_h; // ascent + descent
    uint8_t ascent;
} font_t;

extern const font_t FONT_TITLE; // bold, for the track title
extern const font_t FONT_TEXT;  // everything else

// Decodes the UTF-8 sequence at *p and advances past it. Returns 0 at the
// end of the string, FONT_MISSING for malformed input (skipping one byte).
uint32_t utf8_next(const char **p);

// The glyph to draw for cp: FONT_MISSING's box for anything the font lacks.
const font_glyph_t *font_glyph(const font_t *font, uint32_t cp);

// Width in px of text (sum of advances). 0 for NULL/"".
int font_text_width(const font_t *font, const char *text);
