#!/usr/bin/env python3
"""Generates main/font_data.c from the X11 misc-fixed 6x10 font.

misc-fixed is public domain and ships with X11 as per-charset PCF files; the
ones below cover ASCII, Latin-1, Central European, Turkish, Baltic and
Cyrillic, which is what music tags here use. Glyphs are merged by Unicode
codepoint (first file wins) into one table sorted for binary search, plus a
few hand-drawn ones (ellipsis, playback icons, the missing-glyph box).

Needs Pillow (PcfFontFile), run once by hand; the output is checked in:

    python3 tools/gen_font.py
"""

import codecs
import gzip
import io
import os

from PIL import PcfFontFile

FONT_DIR = "/usr/share/fonts/X11/misc"
CHARSETS = ["ISO8859-1", "ISO8859-2", "ISO8859-5", "ISO8859-9", "ISO8859-13", "ISO8859-15"]
W, H, ASCENT = 6, 10, 8
OUT = os.path.join(os.path.dirname(__file__), "..", "main", "font_data.c")

# Hand-drawn glyphs, 10 rows of 6 px ('#' = lit). Must match the codepoints
# in font.h.
EXTRA = {
    0x2026: [  # horizontal ellipsis
        "......", "......", "......", "......", "......",
        "......", "......", "#.#.#.", "......", "......",
    ],
    0xE000: [  # FONT_ICON_PLAY
        "......", "#.....", "##....", "###...", "####..",
        "###...", "##....", "#.....", "......", "......",
    ],
    0xE001: [  # FONT_ICON_PAUSE
        "......", "##.##.", "##.##.", "##.##.", "##.##.",
        "##.##.", "##.##.", "##.##.", "......", "......",
    ],
    0xE002: [  # FONT_ICON_STOP
        "......", "......", "#####.", "#####.", "#####.",
        "#####.", "#####.", "......", "......", "......",
    ],
    0xFFFD: [  # FONT_MISSING: anything the font doesn't have
        "......", "#####.", "#...#.", "#...#.", "#...#.",
        "#...#.", "#...#.", "#####.", "......", "......",
    ],
}


def load(charset):
    data = gzip.open(os.path.join(FONT_DIR, f"6x10-{charset}.pcf.gz")).read()
    # PIL maps bytes to glyphs through the charset codec, which breaks for
    # non-Latin-1 files; latin-1 keeps it a plain byte index.
    return PcfFontFile.PcfFontFile(io.BytesIO(data), charset_encoding="iso8859-1")


def rows_of(glyph):
    (_, _), (x0, y0, _, _), _, im = glyph
    rows = [0] * H
    for y in range(im.size[1]):
        for x in range(im.size[0]):
            if im.getpixel((x, y)):
                rows[ASCENT + y0 + y] |= 0x80 >> (x0 + x)
    return rows


def main():
    glyphs = {}
    for charset in CHARSETS:
        font = load(charset)
        decode = codecs.getdecoder(charset.replace("ISO", "iso-"))
        for byte in list(range(0x20, 0x7F)) + list(range(0xA0, 0x100)):
            g = font.glyph[byte]
            if not g or byte == 0xAD:  # soft hyphen: never drawn
                continue
            try:
                cp = ord(decode(bytes([byte]))[0])
            except UnicodeDecodeError:
                continue
            glyphs.setdefault(cp, rows_of(g))
    for cp, art in EXTRA.items():
        glyphs[cp] = [sum(0x80 >> x for x, c in enumerate(row) if c == "#") for row in art]

    lines = [
        "// Generated by tools/gen_font.py from the X11 misc-fixed 6x10 font",
        "// (public domain). Don't edit by hand: change the script and rerun it.",
        "",
        '#include "font.h"',
        "",
        "const font_glyph_t FONT_GLYPHS[] = {",
    ]
    for cp in sorted(glyphs):
        rows = ", ".join(f"0x{r:02X}" for r in glyphs[cp])
        name = "icon" if cp >= 0xE000 else "backslash" if cp == 0x5C else "space" if cp == 0x20 else "nbsp" if cp == 0xA0 else chr(cp)
        lines.append(f"    {{0x{cp:04X}, {{{rows}}}}}, // {name}")
    lines += ["};", "", "const int FONT_GLYPH_COUNT = sizeof(FONT_GLYPHS) / sizeof(FONT_GLYPHS[0]);", ""]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"{len(glyphs)} glyphs -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
